#SPDX-License-Identifier: MIT-0
---
# tasks file for network
- name: Create database network
  docker_network:
    name: db-network
    state: present

- name: Create backend network
  docker_network:
    name: backend-network
    state: present

- name: Create proxy network
  docker_network:
    name: proxy-network
    state: present
